### ISSUE TITLE
Make tests fail if the user IDs aren't filled in

### ISSUE THREAD

**Issue by sjl** [MurrayT/SageTest#2]
At exactly 9 PM I realized I didn't fill mine in.

I can't find where it's recording the user IDs in this repo, but if you can point me at it I can send a pull request.

**Comment by MurrayT** [comment]
It's in the shell script. I use some weird stuff with sed that pulls out the username, I think we may change to an array declared at the top of the solutions file to allow us to do that.

**Comment by MurrayT** [comment]
Fixed in 52857115216b1b71fb93d11a119c8a46c6a847b4
Need to pull the repo again, id input will change slightly for future modules.
User handling is done in the sage script, raises runtime error if users not defined properly
